#!/bin/bash

# List of directories for which we want to change the parent directory"s permissions
directories=(
  '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop495/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop519/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/all/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/ld/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/lyso/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/mito/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/nuc/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/perox/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/yolk/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop527/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop536/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop537/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop538/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop540/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop541/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop550/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop496/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop497/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop498/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop515/all/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop534/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop545/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop553/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop554/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop555/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop533/ld/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop521/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop528/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop532/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop533/all/meshes'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop535/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop539/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop542/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop543/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop544/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop556/all/meshes/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop495/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop519/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/all'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/ld'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/lyso'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/mito'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/nuc'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/perox'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop526/yolk'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop527/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop536/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop537/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop538/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop540/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop541/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-bw-1/crop550/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop496/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop497/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop498/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop515/all'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop534/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop545/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop553/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop554/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-comma-1/crop555/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop533/ld'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop521/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop528/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop532/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop533/all'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop535/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop539/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop542/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop543/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop544/all/'
 '/nrs/cellmap/ackermand/new_meshes/meshes/crop_checks/crop_check_updated_20250221/jrc_c-elegans-op50-1/crop556/all/'
)

# Iterate over the list and update the permissions on the parent (one level up) of each directory
for dir in "${directories[@]}"; do
  # Get the parent directory
  echo "Updating permissions recursively for parent directory: $dir"
  chmod u=rwx,g=rwx "$dir"
  parent_dir=$(dirname "$dir")
  
  echo "Updating permissions recursively for parent directory: $parent_dir"
  chmod u=rwx,g=rwx "$parent_dir"
done
