name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Upgrade pip and install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install numpy Cython setuptools wheel build

      - name: Install project
        run: pip install .

      - name: Install test dependencies
        run: pip install pytest

      - name: Run tests
        run: pytest
